config/routes.rb
Grocery::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate', via: [:get, :post]
  
  resources :products do
    collection do
      get 'search'
    end
  end

  resources :users
    
  resources :ratings, only: :update
  
  root 'products#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match 'products/:id/like', to: 'products#like', via: [:get, :post], :as => :like_product
  match 'products/:id/dislike', to: 'products#dislike', via: [:get, :post], :as => :dislike_product
  

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  searchable do
    text :item_name, :default_boost => 2
    text :item_description
  end

  has_many :ratings
  has_many :likes
  has_many :users, :through => :likes
  
  def average_rating
    ratings.sum(:score) / ratings.size
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at) unless auth.credentials.expires_at.nil?
      user.save!
    end
  end
  
  has_many :likes
  has_many :products, :through => :likes
  has_many :ratings
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

helper_method :sort_column, :sort_direction


  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params.permit(:item_name,:item_description))
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end
  
  def show
    @product = Product.find(params[:id])
    @rating = Rating.create(product_id: @product.id, user_id: current_user.id, score: 0)
  end
  
  def like
    @product = Product.find(params[:id])
    if Like.find_by_user_id_and_product_id(current_user.id,@product.id).nil?
      @like = Like.create(product_id: @product.id, user_id: current_user.id)
      flash[:notice] = "You successfully like the product ! "
    else
      flash[:error] = "You have already liked the product ! "
    end
    redirect_to @product
  end
  
  def dislike
    @product = Product.find(params[:id])
    @like = Like.find_by_user_id_and_product_id(current_user.id,@product.id)
    unless @like.nil? 
      @like.delete 
      flash[:notice] = "You successfully dislike the product ! "
    else
      flash[:error] = "You have never liked the product ! "
    end
    redirect_to @product
  end
  
  def index
    @products = Product.order(sort_column + " " + sort_direction)
    @products = @products.paginate(:page => params[:page], :per_page => 10)

  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update(params[:product].permit(:item_name, :item_description))
      redirect_to @product
    else
      render 'edit'
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  
  def search
    @search = Product.search do
      keywords(params[:q])
      paginate(:page => params[:page], :per_page => 25)
    end
    @products = @search.results
  end
  
  private 
  def product_params
    params.require(:product).permit(:item_name,:item_description)
  end
  
  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "item_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def update
    @rating = Rating.find(params[:id])
    @product = @rating.product
    if @rating.update_attributes(score: params[:score])
      respond_to do |format|
        format.js
      end
    flash[:notice] = "Rating successfully recorded"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
    
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

helper_method :sort_column, :sort_direction
  
  def show
    @user = User.find(params[:id])
    @products = @user.products
    @products = @products.order(sort_column + " " + sort_direction)
    @products = @products.paginate(:page => params[:page], :per_page => 15)
  end
  
  private 
  
  def sort_column
    @products.column_names.include?(params[:sort]) ? params[:sort] : "item_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
 <% if current_user %>
    <li><%= image_tag current_user.image %></li>
    <li>&nbsp&nbspWelcome <strong><%= current_user.name %></strong>!</li>
    <li>&nbsp&nbspYour Email Address is at <strong><%= current_user.email %></strong>!</li>
    <li><%= link_to "User profile", user_path(current_user) %></li> 
    <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
  <% else %>
    <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
    <li><%= link_to "Sign in with Twitter", "/auth/twitter", id: "sign_in" %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Find your grocery!" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited
      this product from being saved:</h2>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name %>
  </p>
 
  <p>
    <%= f.label :item_description %><br>
    <%= f.text_area :item_description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/_list.html.erb
<div class="container-fluid">
<div class="row-fluid">
<div class="span12">
<table class="container-fluid table table-striped table-hover">
  <tr class="row-fluid">
    <th class="span10"><%= sortable "item_name" %></th>
    <th class="span2"><%= sortable "price" %></th>
    <th class="span2"><%= sortable "likes_count" %></th>
    <th class="span4">Actions</th>
  </tr>
 
<% @products.each do |product| %>
  <tr class="row-fluid">
    <td><%= product.item_name %></td>
    <td><i><%= product.currency_code %></i> <%= product.price %></td>
    <td style="text-align:center;"><%= product.likes_count ? product.likes_count : "0" %></td>
    <td>
      <div style="float:left;">
        <%= button_to "Show", product_path(product), :class => "btn btn-primary", :method => :get %>
      </div>
      <div style="float:left;">
        <%= button_to "Like", like_product_path(product), :class => "btn btn-success", :method => :get %>
      </div>
      <div style="float:left;">
        <%= button_to "Dislike", dislike_product_path(product), :class => "btn btn-danger", :method => :get %></td>
      </div>
      <div style="clear:both;">
      </div>
  </tr>
<% end %>
</table>
<br>
<%= will_paginate @products %>
</div>
</div>
</div>

app/views/products/_search_form.html.erb
<%= form_tag search_products_path, :method => :get do %>
  <p>
    <%= text_field_tag :q, params[:q], options ={ :placeholder => "Search here" } %>
    <%= button_tag(type: "submit", class: "btn btn-default") do %>
      <i class="icon-search"></i>
    <% end %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<p>
<% @product.temp_img_urls.strip.split(/\s+/).each do |p| %>
  <%= link_to image_tag(p), @product.source_url %>
<% end %>
</p>
<p> 
<%= render 'form' %>
 
<%= link_to 'Back', product_path(@product) %>

app/views/products/index.html.erb
<%= render 'search_form' %>
<h1>Listing All Products</h1>
<%= render 'list' %>

app/views/products/new.html.erb
<h1>New product</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<%= render 'search_form' %>
<h1>Listing All Search Results</h1>
<%= render 'list' %>

app/views/products/show.html.erb
<%= render 'search_form' %>
<head>
<script>
  $('#star').raty({
    readOnly: true,
    score: <%= @product.average_rating %>,
    path: '/assets'
  });

  $('#user_star').raty({
    score: <%= @rating.score %>,
    path: '/assets',
    click: function(score, evt) {
      $.ajax({
        url: '/ratings/' + <%= @rating.id %>,
        type: 'PATCH',
        data: { score: score }
      });
    }
  });
</script>
</head>
<p>
<% @product.temp_img_urls.strip.split(/\s+/).each do |p| %>
  <%= link_to image_tag(p), @product.source_url %>
<% end %>
</p>
<p>
  <strong>Item Name:</strong>
  <%= @product.item_name %>
</p>
 
<p>
  <strong>Item Description:</strong>
  <%= @product.item_description %>
</p>

<p>
  <strong>Price:</strong>
  <i><%= @product.currency_code %></i>
  <%= @product.price %>
</p>

<p>Averate rating</p>
<div id="star"></div>

<p>Your rating</p>
<div id="user_star"></div>

 
<%= link_to 'Edit Product', edit_product_path(@product) %> |
<%= link_to 'Like Product', like_product_path(@product) %> |
<%= link_to 'Back to Products', products_path %> |
<%= link_to 'Back', :back %> 
<br>

app/views/users/show.html.erb
<%= render 'products/search_form' %>
<p>
  <strong>Member since:</strong>
  <%= @user.created_at %>
</p>

<p>
  <strong>Last change since:</strong>
  <%= @user.updated_at %>
</p>

<h1>Listing Likes</h1>
<%= render 'products/list' %>
<br>
<%= link_to 'Back to Products', products_path %> |
<%= link_to 'Back', :back %> |